Feature/nftpar 516
UniqueNetwork/marketplace-backend pull request #12
Opened 2021-07-14 06:52 UTC by Atomosk

Unique escrow now runs tasks in parallel at some degree.

2021-07-21 13:19 UTC, usetech-llc requested changes

2021-07-21 13:19 UTC, usetech-llc commented on src/Marketplace.Escrow.JS.Unique/unique/index.js
> +    await this.sendAsAdmin(tx);
Так не работает. Сейчас админ у контракта вообще один, а будут разные наборы админов у контракта и коллекции.

2021-07-21 13:20 UTC, usetech-llc commented
Также нужны автотесты на параллелизм. Сейчас цель тестов - убедиться, что при попытке распараллеливания (с одним админом) ничего не ломается.

2021-07-22 02:37 UTC, Atomosk commented
Тест есть в ветке hotfix/NFTPAR-583, там три пользователя одновременно отправляют токен, вызывают ask и cancel. Именно так я вычислил что сразу после того как колбек отправки транзакции отработал отправлять следующую еще нельзя, а вот во второй вызов колбека уже можно, хотя еще и не известно успешна ли транзакция или нет. Поэтому админ обратно в пул возвращается с таким странным условием, чтобы побыстрее.

2021-08-25 11:50 UTC, usetech-llc commented on src/Marketplace.Escrow.JS.Unique/unique/admin_pool.js
> +    this.mainAdminGroupId = 'mainAdmin';
Что такое main admin?

2021-09-01 10:50 UTC, usetech-llc approved these changes

2021-09-01 10:52 UTC, merged